feat: Add multi tenancy to S3
awslabs/fhir-works-on-aws-persistence-ddb pull request #87
Opened 2021-06-18 17:55 UTC by Bingjiling

Issue #, if available:

Description of changes:

* Update S3 to support multi-tenancy 
* Update unit test 
* WIP: update GH workflow to checkout interface package locally 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-06-21 17:07 UTC, carvantes requested changes
Overall looks good, but I think changes are needed for the delete operation.

2021-06-21 17:07 UTC, carvantes commented on src/objectStorageService/s3DataService.ts
>          await S3ObjectStorageService.deleteBasedOnPrefix(request.id);
delete should consider the `tenantId`

2021-06-21 17:09 UTC, Bingjiling commented on src/objectStorageService/s3DataService.ts
>          await S3ObjectStorageService.deleteBasedOnPrefix(request.id);
Good catch! Updating now...

2021-06-21 21:02 UTC, rsmayda commented on src/objectStorageService/s3DataService.test.ts
> +        expect(response.resource.meta).toBeDefined();
Nit: may be able to shorten your tests by use [strictEqual](https://jestjs.io/docs/expect#tostrictequalvalue)

2021-06-22 03:10 UTC, carvantes approved these changes

2021-06-22 14:10 UTC, merged